apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: music
spec:
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
      name: navidrome
  type: ClusterIP
